name: nexus_legend
description: "An application for the project \"laboratorio integrato\""

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.4
  flutter_bloc: ^8.1.0
  equatable: ^2.0.5
  firebase_core: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/


